# 服务配置
server:
  port: 9898
  
# Spring相关配置
spring:
  application:
    name: kafka-service
  profiles: 
    active: dev
  #datasource:
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    #url: jdbc:oracle:thin:@192.168.2.108:1521:ORCL
    #username: portal_invt
    #password: portal_invt
    #hikari: 
      #connection-test-query: SELECT 1 FROM DUAL  
  # kafka  
  kafka:
    bootstrap-servers: 192.168.2.6:9092
    consumer: 
      group-id: ${spring.application.name}-consumner
      #auto-offset-reset: latest
      auto-offset-reset: earliest
      enable-auto-commit: true
      #value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.LongDeserializer
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: org.apache.kafka.common.serialization.LongDeserializer
    #producer: 
      #value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties: 
      # 如果不配置下面两个属性，则会出现：B cannot be cast to java.lang.String的错误
      default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
# 集成MyBatis  
mybatis:   
  mapperLocations: classpath*:mybatis/mapper/**/*.xml
  typeAliasesPackage: com.hengzhiyi.it.website.model
  #configLocation: classpath:mybatis/config/mybatis-config.xml
  configuration-properties: 
    # 数据库方言
    helperDialect: oracle 
    # RowBounds参数offset作为PageNum使用 - 默认不使用
    offsetAsPageNum: true 
    # RowBounds是否进行count查询 - 默认不查询
    rowBoundsWithCount: true
    # 当设置为true的时候，如果pagesize设置为0（或RowBounds的limit=0），就不执行分页，返回全部结果
    pageSizeZero: false
    # 分页合理化
    reasonable: false
    # 是否支持接口参数来传递分页参数，默认false
    supportMethodsArguments: false      
# 日志配置
logging: 
  config: classpath:log-config/logback-${spring.profiles.active}.xml
  level:
    org.apache.kafka.clients.consumer: error